### ISSUE TITLE
 illegal memory encountered randomly during runtime.

### ISSUE THREAD

**Issue by synsin0** [DNMP/DNMP#2]
I'd like to train geometry on waymo dataset. My device is a single A100-80G. But illegal memory encountered randomly. I guess it is a GPU memory issue. Only when I decrease num_ray and chunk_size from 16384(our suppl. material said) to 512, the training process goes all right. May you provide some instructions on this issue?

[9] Optimize 32132 voxels
[10] 
[11]   0%|          | 0/73 [00:00<?, ?it/s]
[12]   1%|▏         | 1/73 [00:06<07:34,  6.32s/it]
[13]   3%|▎         | 2/73 [00:09<05:21,  4.53s/it]
[14]   4%|▍         | 3/73 [00:12<04:35,  3.93s/it]
[15]   5%|▌         | 4/73 [00:16<04:16,  3.72s/it]
[16]   5%|▌         | 4/73 [00:20<05:53,  5.12s/it]
[17] Traceback (most recent call last):
[18]   File "/defaultShare/SHFP12/yining.shi/DNMP/train_geo.py", line 12, in <module>
[19]     trainer.train()
[20]   File "/defaultShare/SHFP12/yining.shi/DNMP/core/trainer_geometry.py", line 225, in train
[21]     loss_meter.update(loss.item())              
[22] RuntimeError: CUDA error: an illegal memory access was encountered
[23] CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
[24] For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by DNMP** [comment]
We haven't encountered this issue. However, due to significant code refactoring before the release, there might be some bugs. We will check this issue and get back to you ASAP.

**Comment by FanLu97** [comment]
@synsin0 
We have tested the current version and the code runs as expected. Our current training log for `seq_1` of Waymo dataset is:
![image](https://github.com/DNMP/DNMP/assets/45007531/e8540765-54c8-4855-b009-70f29081aa79)

**Comment by rockywind** [comment]
I met the error when the code run 11 hours.
![image](https://github.com/DNMP/DNMP/assets/14838781/38ce9e04-e32a-499e-836f-d90fb0377e9f)
![image](https://github.com/DNMP/DNMP/assets/14838781/d91a8388-cdce-438b-be5f-7a987d13af45)

**Comment by FanLu97** [comment]
@rockywind 
It seems that you have successfully run the training for rendering? The error should be caused by different version of scikit-image. You can try downgrade scikit-image to 0.19/0.18.

**Comment by rockywind** [comment]
Thanks I have a try!
